import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import React from 'react';
import Providers from '@/utils/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next What Movie App',
  description: 'Generated by create next app and storybook',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div id={'wrap'}>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
